server:
  port: 8080

management:
  security:
    enabled: false

spring:
  application:
    name: client-zx
#  boot:
#    admin:
#      url: http://127.0.0.1:1111

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://server1:1111/eureka/,http://server2:1112/eureka/,http://server3:1113/eureka/




