#集群配置-节点1
server:
  port: 1111
#management:
#  security:
#    enabled: false
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: server1
  client:
      service-url:
        defaultZone: http://server2:1112/eureka/,http://server3:1113/eureka/







