spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BrightStarry/SpringCloud.git
          default-label: master
server:
  port: 6666
